name: Build Test and Publish Coverage Report

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write
      id-token: write

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Build and Run Tests
        run: mvn clean verify

      - name: Prepare Coverage Report
        run: |
          mkdir public
          cp -r target/jacoco-report/* public/

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4